server:
  port: 8010

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!
    oauth2:
      client:
        registration:
          google:
            clientId: 502203645662-3hbk4td7qmhokfadvoic8so9dmibuvqj.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            clientId: qMn96inY8WsITZW2gWB9
            clientSecret: _cflUXTgw9
            scope:
              - email
              - name
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8010/login/oauth2/code/naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database.cheqn470hyme.ap-northeast-1.rds.amazonaws.com/shopping
    username: admin2
    password: ghtmd12!

mybatis:
  mapper-locations:
    - /mappers/*.xml


